/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 05-kwi-2026 17:19:45 				*/
/*  DBMS       : MSAccess 						*/
/* ---------------------------------------------------- */

ALTER TABLE [ActiveDirectory] DROP CONSTRAINT [FK_Active Directory_posiada];

ALTER TABLE [DaneUwietrzytelniania] DROP CONSTRAINT [FK_Dane uwietrzytelniania_zawiera];

ALTER TABLE [HistoriaUrządzenia] DROP CONSTRAINT [FK_Historia urządzenia_posiada];

ALTER TABLE [Kierownik] DROP CONSTRAINT [FK_Kierownik_Osoba];

ALTER TABLE [Pracownik] DROP CONSTRAINT [FK_Pracownik_Osoba];

ALTER TABLE [ProcesOffboardingu] DROP CONSTRAINT [FK_Proces offboardingu_podlega];

ALTER TABLE [ProcesOffboardingu] DROP CONSTRAINT [FK_Proces offboardingu_rozlicza];

ALTER TABLE [ProtokółZwrotu] DROP CONSTRAINT [FK_Protokół zwrotu_generuje];

ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_generuje];

ALTER TABLE [Raport] DROP CONSTRAINT [FK_Raport_zawiera];

ALTER TABLE [SpecjalistaHelpdesk] DROP CONSTRAINT [FK_Specjalista helpdesk_Osoba];

ALTER TABLE [Urządzenie] DROP CONSTRAINT [FK_Urządzenie_wydaje];

ALTER TABLE [Urządzenie] DROP CONSTRAINT [FK_Urządzenie_zawiera];

ALTER TABLE [Wniosek] DROP CONSTRAINT [FK_Wniosek_akceptuje];

ALTER TABLE [Wniosek] DROP CONSTRAINT [FK_Wniosek_składa];

ALTER TABLE [Wypożyczenie] DROP CONSTRAINT [FK_Wypożyczenie_posiada];

ALTER TABLE [Wypożyczenie] DROP CONSTRAINT [FK_Wypożyczenie_dotyczy];

ALTER TABLE [Wypożyczenie] DROP CONSTRAINT [FK_Wypożyczenie_skutkuje];

DROP TABLE [VIEW_A];

DROP TABLE [ActiveDirectory];

DROP TABLE [DaneUwietrzytelniania];

DROP TABLE [HistoriaUrządzenia];

DROP TABLE [Kierownik];

DROP TABLE [Osoba];

DROP TABLE [Pracownik];

DROP TABLE [ProcesOffboardingu];

DROP TABLE [ProtokółZwrotu];

DROP TABLE [Raport];

DROP TABLE [SpecjalistaHelpdesk];

DROP TABLE [Urządzenie];

DROP TABLE [Wniosek];

DROP TABLE [Wypożyczenie];

DROP TABLE [Zasoby];

CREATE TABLE [ActiveDirectory]
(
	[Login] varchar NULL,
	[StatusKonta] varchar NULL,
	[ActiveDirectoryID] varchar NOT NULL,
	[OsobaID] varchar NOT NULL
);

CREATE TABLE [DaneUwietrzytelniania]
(
	[DaneUżytkwnika] varchar NULL,
	[DaneUwietrzytelnianiaID] varchar NOT NULL,
	[ActiveDirectoryID] varchar NOT NULL
);

CREATE TABLE [HistoriaUrządzenia]
(
	[DataWpisu] varchar NULL,
	[HistoriaUrządzeniaID] varchar NOT NULL,
	[UrządzenieID] varchar NOT NULL
);

CREATE TABLE [Kierownik]
(
	[Dział] varchar NULL,
	[KierownikID] varchar NOT NULL
);

CREATE TABLE [Osoba]
(
	[Imię] varchar NULL,
	[Nazwisko] varchar NULL,
	[OsobaID] varchar NOT NULL
);

CREATE TABLE [Pracownik]
(
	[IdAd] varchar NULL,
	[Stanowisko] varchar NULL,
	[PracownikID] varchar NOT NULL
);

CREATE TABLE [ProcesOffboardingu]
(
	[DataRozliczenia] varchar NULL,
	[StatusZwrotu] varchar NULL,
	[ProcesOffboardinguID] varchar NOT NULL,
	[PracownikID] varchar NULL,
	[SpecjalistaHelpdeskID] varchar NULL
);

CREATE TABLE [ProtokółZwrotu]
(
	[Podpis] varchar NULL,
	[ProtokółZwrotuID] varchar NOT NULL,
	[ProcesOffboardinguID] varchar NOT NULL
);

CREATE TABLE [Raport]
(
	[DataGenerowania] varchar NULL,
	[TypRaportu] varchar NULL,
	[RaportID] varchar NOT NULL,
	[SpecjalistaHelpdeskID] varchar NULL,
	[ZasobyID] varchar NULL
);

CREATE TABLE [SpecjalistaHelpdesk]
(
	[Identyfikator] varchar NULL,
	[Rola] varchar NULL,
	[SpecjalistaHelpdeskID] varchar NOT NULL
);

CREATE TABLE [Urządzenie]
(
	[Kod] varchar NULL,
	[Status] varchar NULL,
	[UrządzenieID] varchar NOT NULL,
	[SpecjalistaHelpdeskID] varchar NULL,
	[ZasobyID] varchar NULL
);

CREATE TABLE [Wniosek]
(
	[DataZłożenia] varchar NULL,
	[Status] varchar NULL,
	[Uzasadnienie] varchar NULL,
	[WniosekID] varchar NOT NULL,
	[KierownikID] varchar NULL,
	[PracownikID] varchar NULL
);

CREATE TABLE [Wypożyczenie]
(
	[DataWypożyczenia] varchar NULL,
	[DataZwrotu] varchar NULL,
	[WypożyczenieID] varchar NOT NULL,
	[PracownikID] varchar NULL,
	[UrządzenieID] varchar NULL,
	[WniosekID] varchar NULL
);

CREATE TABLE [Zasoby]
(
	[DaneUżytkownika] varchar NULL,
	[RaportyUżytkownika] varchar NULL,
	[SprzętUżytkownika] varchar NULL,
	[ZasobyID] varchar NOT NULL
);

ALTER TABLE [ActiveDirectory] ADD CONSTRAINT [PK_ActiveDirectory]
	PRIMARY KEY ([ActiveDirectoryID]);

ALTER TABLE [DaneUwietrzytelniania] ADD CONSTRAINT [PK_DaneUwietrzytelniania]
	PRIMARY KEY ([DaneUwietrzytelnianiaID]);

ALTER TABLE [HistoriaUrządzenia] ADD CONSTRAINT [PK_HistoriaUrządzenia]
	PRIMARY KEY ([HistoriaUrządzeniaID]);

ALTER TABLE [Kierownik] ADD CONSTRAINT [PK_Kierownik]
	PRIMARY KEY ([KierownikID]);

ALTER TABLE [Osoba] ADD CONSTRAINT [PK_Osoba]
	PRIMARY KEY ([OsobaID]);

ALTER TABLE [Pracownik] ADD CONSTRAINT [PK_Pracownik]
	PRIMARY KEY ([PracownikID]);

ALTER TABLE [ProcesOffboardingu] ADD CONSTRAINT [PK_ProcesOffboardingu]
	PRIMARY KEY ([ProcesOffboardinguID]);

ALTER TABLE [ProtokółZwrotu] ADD CONSTRAINT [PK_ProtokółZwrotu]
	PRIMARY KEY ([ProtokółZwrotuID]);

ALTER TABLE [Raport] ADD CONSTRAINT [PK_Raport]
	PRIMARY KEY ([RaportID]);

ALTER TABLE [SpecjalistaHelpdesk] ADD CONSTRAINT [PK_SpecjalistaHelpdesk]
	PRIMARY KEY ([SpecjalistaHelpdeskID]);

ALTER TABLE [Urządzenie] ADD CONSTRAINT [PK_Urządzenie]
	PRIMARY KEY ([UrządzenieID]);

ALTER TABLE [Wniosek] ADD CONSTRAINT [PK_Wniosek]
	PRIMARY KEY ([WniosekID]);

ALTER TABLE [Wypożyczenie] ADD CONSTRAINT [PK_Wypożyczenie]
	PRIMARY KEY ([WypożyczenieID]);

ALTER TABLE [Zasoby] ADD CONSTRAINT [PK_Zasoby]
	PRIMARY KEY ([ZasobyID]);

ALTER TABLE [ActiveDirectory] ADD CONSTRAINT [FK_Active Directory_posiada]
	FOREIGN KEY ([OsobaID]) REFERENCES [Osoba] ([OsobaID]);

ALTER TABLE [DaneUwietrzytelniania] ADD CONSTRAINT [FK_Dane uwietrzytelniania_zawiera]
	FOREIGN KEY ([ActiveDirectoryID]) REFERENCES [ActiveDirectory] ([ActiveDirectoryID]);

ALTER TABLE [HistoriaUrządzenia] ADD CONSTRAINT [FK_Historia urządzenia_posiada]
	FOREIGN KEY ([UrządzenieID]) REFERENCES [Urządzenie] ([UrządzenieID]);

ALTER TABLE [Kierownik] ADD CONSTRAINT [FK_Kierownik_Osoba]
	FOREIGN KEY ([KierownikID]) REFERENCES [Osoba] ([OsobaID]);

ALTER TABLE [Pracownik] ADD CONSTRAINT [FK_Pracownik_Osoba]
	FOREIGN KEY ([PracownikID]) REFERENCES [Osoba] ([OsobaID]);

ALTER TABLE [ProcesOffboardingu] ADD CONSTRAINT [FK_Proces offboardingu_podlega]
	FOREIGN KEY ([PracownikID]) REFERENCES [Pracownik] ([PracownikID]);

ALTER TABLE [ProcesOffboardingu] ADD CONSTRAINT [FK_Proces offboardingu_rozlicza]
	FOREIGN KEY ([SpecjalistaHelpdeskID]) REFERENCES [SpecjalistaHelpdesk] ([SpecjalistaHelpdeskID]);

ALTER TABLE [ProtokółZwrotu] ADD CONSTRAINT [FK_Protokół zwrotu_generuje]
	FOREIGN KEY ([ProcesOffboardinguID]) REFERENCES [ProcesOffboardingu] ([ProcesOffboardinguID]);

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_generuje]
	FOREIGN KEY ([SpecjalistaHelpdeskID]) REFERENCES [SpecjalistaHelpdesk] ([SpecjalistaHelpdeskID]);

ALTER TABLE [Raport] ADD CONSTRAINT [FK_Raport_zawiera]
	FOREIGN KEY ([ZasobyID]) REFERENCES [Zasoby] ([ZasobyID]);

ALTER TABLE [SpecjalistaHelpdesk] ADD CONSTRAINT [FK_Specjalista helpdesk_Osoba]
	FOREIGN KEY ([SpecjalistaHelpdeskID]) REFERENCES [Osoba] ([OsobaID]);

ALTER TABLE [Urządzenie] ADD CONSTRAINT [FK_Urządzenie_wydaje]
	FOREIGN KEY ([SpecjalistaHelpdeskID]) REFERENCES [SpecjalistaHelpdesk] ([SpecjalistaHelpdeskID]);

ALTER TABLE [Urządzenie] ADD CONSTRAINT [FK_Urządzenie_zawiera]
	FOREIGN KEY ([ZasobyID]) REFERENCES [Zasoby] ([ZasobyID]);

ALTER TABLE [Wniosek] ADD CONSTRAINT [FK_Wniosek_akceptuje]
	FOREIGN KEY ([KierownikID]) REFERENCES [Kierownik] ([KierownikID]);

ALTER TABLE [Wniosek] ADD CONSTRAINT [FK_Wniosek_składa]
	FOREIGN KEY ([PracownikID]) REFERENCES [Pracownik] ([PracownikID]);

ALTER TABLE [Wypożyczenie] ADD CONSTRAINT [FK_Wypożyczenie_posiada]
	FOREIGN KEY ([PracownikID]) REFERENCES [Pracownik] ([PracownikID]);

ALTER TABLE [Wypożyczenie] ADD CONSTRAINT [FK_Wypożyczenie_dotyczy]
	FOREIGN KEY ([UrządzenieID]) REFERENCES [Urządzenie] ([UrządzenieID]);

ALTER TABLE [Wypożyczenie] ADD CONSTRAINT [FK_Wypożyczenie_skutkuje]
	FOREIGN KEY ([WniosekID]) REFERENCES [Wniosek] ([WniosekID]);

CREATE VIEW VIEW_A AS 
/* SQL statements defining VIEW_A */;
