///////////////////////////////////////////////////////////
//  FormularzPPrac_OceñZasadnoœæ.cs
//  Implementation of the Class FormularzPPrac_OceñZasadnoœæ
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:36
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzPPrac_OceñZasadnoœæ {

		private int Ocena zasadnoœci;

		public FormularzPPrac_OceñZasadnoœæ(){

		}

		~FormularzPPrac_OceñZasadnoœæ(){

		}

		public void Ocena wniosku(){

		}

		public Ster_OceñZasadnoœæ Ster_OceñZasadnoœæ{
			get{
				return m_Ster_OceñZasadnoœæ;
			}
			set{
				m_Ster_OceñZasadnoœæ = value;
			}
		}

	}//end FormularzPPrac_OceñZasadnoœæ

}//end namespace Interfejsy