///////////////////////////////////////////////////////////
//  FormluarzPrac_PobierzDane.cs
//  Implementation of the Class FormluarzPrac_PobierzDane
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:04
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormluarzPrac_PobierzDane {

		private char Dane pracownika;

		public FormluarzPrac_PobierzDane(){

		}

		~FormluarzPrac_PobierzDane(){

		}

		public void Odbierz dane(){

		}

		public void Za¿¹daj Danych(){

		}

	}//end FormluarzPrac_PobierzDane

}//end namespace Interfejsy