///////////////////////////////////////////////////////////
//  FormlarzSpecDesk_RozliczZwrot.cs
//  Implementation of the Class FormlarzSpecDesk_RozliczZwrot
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 16:59:25
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormlarzSpecDesk_RozliczZwrot {

		private int Stan sprzêtów;

		public FormlarzSpecDesk_RozliczZwrot(){

		}

		~FormlarzSpecDesk_RozliczZwrot(){

		}

		public void Aktualizuj dane(){

		}

	}//end FormlarzSpecDesk_RozliczZwrot

}//end namespace Interfejsy