///////////////////////////////////////////////////////////
//  FormularzAD_ZainicjujRozliczenie.cs
//  Implementation of the Class FormularzAD_ZainicjujRozliczenie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:20
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzAD_ZainicjujRozliczenie {

		private int Lista sprzêtów;
		private char Status zatrudnienia;

		public FormularzAD_ZainicjujRozliczenie(){

		}

		~FormularzAD_ZainicjujRozliczenie(){

		}

	}//end FormularzAD_ZainicjujRozliczenie

}//end namespace Interfejsy