///////////////////////////////////////////////////////////
//  FormularzSys_WyœwietlZasoby.cs
//  Implementation of the Class FormularzSys_WyœwietlZasoby
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:47
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSys_WyœwietlZasoby {

		public FormularzSys_WyœwietlZasoby(){

		}

		~FormularzSys_WyœwietlZasoby(){

		}

		public void Poproœ o Zasoby U¿ytkownika(){

		}

	}//end FormularzSys_WyœwietlZasoby

}//end namespace Interfejsy