///////////////////////////////////////////////////////////
//  FormularzPrac_WyœwietlZasoby.cs
//  Implementation of the Class FormularzPrac_WyœwietlZasoby
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:54
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzPrac_WyœwietlZasoby {

		public FormularzPrac_WyœwietlZasoby(){

		}

		~FormularzPrac_WyœwietlZasoby(){

		}

		public void Wyœwietl zasoby(){

		}

	}//end FormularzPrac_WyœwietlZasoby

}//end namespace Interfejsy