///////////////////////////////////////////////////////////
//  FormularzPrac_Z³ó¿Wniosek.cs
//  Implementation of the Class FormularzPrac_Z³ó¿Wniosek
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:59
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Interfejsy;
namespace Interfejsy {
	public class FormularzPrac_Z³ó¿Wniosek {

		private char Lista sprzêtów;
		private Interfejsy.FormularzAD_Z³ó¿Wniosek m_FormularzAD_Z³ó¿Wniosek;

		public FormularzPrac_Z³ó¿Wniosek(){

		}

		~FormularzPrac_Z³ó¿Wniosek(){

		}

		public FormularzAD_Z³ó¿Wniosek FormularzAD_Z³ó¿Wniosek{
			get{
				return m_FormularzAD_Z³ó¿Wniosek;
			}
			set{
				m_FormularzAD_Z³ó¿Wniosek = value;
			}
		}

		public void WniosekPrac(){

		}

	}//end FormularzPrac_Z³ó¿Wniosek

}//end namespace Interfejsy