///////////////////////////////////////////////////////////
//  FormularzPrac_Przeka¿Sprzêt.cs
//  Implementation of the Class FormularzPrac_Przeka¿Sprzêt
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:49
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzPrac_Przeka¿Sprzêt {

		private int Lista sprzêtów;

		public FormularzPrac_Przeka¿Sprzêt(){

		}

		~FormularzPrac_Przeka¿Sprzêt(){

		}

		public void Urz¹dzeniePrac(){

		}

	}//end FormularzPrac_Przeka¿Sprzêt

}//end namespace Interfejsy