///////////////////////////////////////////////////////////
//  FormularzAD_Z³ó¿Wniosek.cs
//  Implementation of the Class FormularzAD_Z³ó¿Wniosek
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:27
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzAD_Z³ó¿Wniosek {

		private char Lista sprzêtów;

		public FormularzAD_Z³ó¿Wniosek(){

		}

		~FormularzAD_Z³ó¿Wniosek(){

		}

		public void Przypisz wniosek(){

		}

	}//end FormularzAD_Z³ó¿Wniosek

}//end namespace Interfejsy