///////////////////////////////////////////////////////////
//  FormularzSpecDesk_WydajSprzêt.cs
//  Implementation of the Class FormularzSpecDesk_WydajSprzêt
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:08
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSpecDesk_WydajSprzêt {

		private int ID wniosku;
		private int Lista sprzêtów;

		public FormularzSpecDesk_WydajSprzêt(){

		}

		~FormularzSpecDesk_WydajSprzêt(){

		}

		public void ZatwierdŸ wydanie sprzêtów(){

		}

	}//end FormularzSpecDesk_WydajSprzêt

}//end namespace Interfejsy