///////////////////////////////////////////////////////////
//  FormlarzSys_RozliczZwrot.cs
//  Implementation of the Class FormlarzSys_RozliczZwrot
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 16:59:34
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormlarzSys_RozliczZwrot {

		private int Stan sprzêtów;

		public FormlarzSys_RozliczZwrot(){

		}

		~FormlarzSys_RozliczZwrot(){

		}

		public void Rozliczenie(){

		}

	}//end FormlarzSys_RozliczZwrot

}//end namespace Interfejsy