///////////////////////////////////////////////////////////
//  FormularzSys_WydajSprzêt.cs
//  Implementation of the Class FormularzSys_WydajSprzêt
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:39
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSys_WydajSprzêt {

		private int Lista sprzêtu;

		public FormularzSys_WydajSprzêt(){

		}

		~FormularzSys_WydajSprzêt(){

		}

		public void Generuj protokó³(){

		}

		public void Zarejestruj wydanie(){

		}

	}//end FormularzSys_WydajSprzêt

}//end namespace Interfejsy