///////////////////////////////////////////////////////////
//  FormularzAD_WyœwietlZasoby.cs
//  Implementation of the Class FormularzAD_WyœwietlZasoby
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:15
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzAD_WyœwietlZasoby {

		private char dane u¿ytkownika;

		public FormularzAD_WyœwietlZasoby(){

		}

		~FormularzAD_WyœwietlZasoby(){

		}

		public void Autoryzuj u¿ytkownika(){

		}

	}//end FormularzAD_WyœwietlZasoby

}//end namespace Interfejsy