///////////////////////////////////////////////////////////
//  FormluarzAD_PobierzDane.cs
//  Implementation of the Class FormluarzAD_PobierzDane
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 16:59:59
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormluarzAD_PobierzDane {

		private char Dane pracownika;

		public FormluarzAD_PobierzDane(){

		}

		~FormluarzAD_PobierzDane(){

		}

		public void Autoryzuj U¿ytkownika(){

		}

	}//end FormluarzAD_PobierzDane

}//end namespace Interfejsy