///////////////////////////////////////////////////////////
//  FormularzSpecDesk_ZweryfikujDostêpnoœæ.cs
//  Implementation of the Class FormularzSpecDesk_ZweryfikujDostêpnoœæ
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:30
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSpecDesk_ZweryfikujDostêpnoœæ {

		private int Lista sprzêtów;

		public FormularzSpecDesk_ZweryfikujDostêpnoœæ(){

		}

		~FormularzSpecDesk_ZweryfikujDostêpnoœæ(){

		}

		public void SprawdŸ dostêpnoœæ(){

		}

		public void Zwróæ dostêpnoœæ(){

		}

	}//end FormularzSpecDesk_ZweryfikujDostêpnoœæ

}//end namespace Interfejsy