///////////////////////////////////////////////////////////
//  FormularzSys_WygenerjProtoko造.cs
//  Implementation of the Class FormularzSys_WygenerjProtoko造
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:43
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSys_WygenerjProtoko造 {

		public FormularzSys_WygenerjProtoko造(){

		}

		~FormularzSys_WygenerjProtoko造(){

		}

		public void Za蕨daj Protoko堯w(){

		}

	}//end FormularzSys_WygenerjProtoko造

}//end namespace Interfejsy