///////////////////////////////////////////////////////////
//  FormularzSpecDesk_ZainicjujRozliczenie.cs
//  Implementation of the Class FormularzSpecDesk_ZainicjujRozliczenie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:18
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSpecDesk_ZainicjujRozliczenie {

		private int Lista sprzêtów;
		private char Status zatrdnienia;

		public FormularzSpecDesk_ZainicjujRozliczenie(){

		}

		~FormularzSpecDesk_ZainicjujRozliczenie(){

		}

		public void Rozliczenie(){

		}

	}//end FormularzSpecDesk_ZainicjujRozliczenie

}//end namespace Interfejsy