///////////////////////////////////////////////////////////
//  FormularzSpecDesk_DezaktywjKonto.cs
//  Implementation of the Class FormularzSpecDesk_DezaktywjKonto
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:04
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSpecDesk_DezaktywjKonto {

		private char Status zatrudnienia;

		public FormularzSpecDesk_DezaktywjKonto(){

		}

		~FormularzSpecDesk_DezaktywjKonto(){

		}

		public void Dezaktywacja konta(){

		}

	}//end FormularzSpecDesk_DezaktywjKonto

}//end namespace Interfejsy