///////////////////////////////////////////////////////////
//  FormularzPPrac_WygenerujRaporty.cs
//  Implementation of the Class FormularzPPrac_WygenerujRaporty
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:44
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzPPrac_WygenerujRaporty {

		private char Dane pracownika;
		private int Lista sprzêtów;

		public FormularzPPrac_WygenerujRaporty(){

		}

		~FormularzPPrac_WygenerujRaporty(){

		}

		public void Za¿¹daj raportów(){

		}

	}//end FormularzPPrac_WygenerujRaporty

}//end namespace Interfejsy