///////////////////////////////////////////////////////////
//  FormluarzSys_PobierzDane.cs
//  Implementation of the Class FormluarzSys_PobierzDane
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:00:10
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormluarzSys_PobierzDane {

		private char Dane pracownika;

		public FormluarzSys_PobierzDane(){

		}

		~FormluarzSys_PobierzDane(){

		}

		public void Pobierz Dane(){

		}

	}//end FormluarzSys_PobierzDane

}//end namespace Interfejsy