///////////////////////////////////////////////////////////
//  FormularzSys_DezaktywjKonto.cs
//  Implementation of the Class FormularzSys_DezaktywjKonto
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:34
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSys_DezaktywjKonto {

		private char Status zatrudnienia;

		public FormularzSys_DezaktywjKonto(){

		}

		~FormularzSys_DezaktywjKonto(){

		}

		public void Usuñ dane pracownika(){

		}

	}//end FormularzSys_DezaktywjKonto

}//end namespace Interfejsy