///////////////////////////////////////////////////////////
//  FormularzSpecDesk_WygenerujRaporty.cs
//  Implementation of the Class FormularzSpecDesk_WygenerujRaporty
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:12
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSpecDesk_WygenerujRaporty {

		private char Dane pracownika;
		private int Lista sprzêtów;

		public FormularzSpecDesk_WygenerujRaporty(){

		}

		~FormularzSpecDesk_WygenerujRaporty(){

		}

		public void Akceptuj i generuj Raporty(){

		}

		public void Wyœwietl Raporty(){

		}

	}//end FormularzSpecDesk_WygenerujRaporty

}//end namespace Interfejsy