///////////////////////////////////////////////////////////
//  FormularzSpecDesk_ZarejestrujUrz¹dzenie.cs
//  Implementation of the Class FormularzSpecDesk_ZarejestrujUrz¹dzenie
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:22
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSpecDesk_ZarejestrujUrz¹dzenie {

		private int Lista sprzêtów;

		public FormularzSpecDesk_ZarejestrujUrz¹dzenie(){

		}

		~FormularzSpecDesk_ZarejestrujUrz¹dzenie(){

		}

		public void Zarejestruj nowe urzadzenie(){

		}

	}//end FormularzSpecDesk_ZarejestrujUrz¹dzenie

}//end namespace Interfejsy