///////////////////////////////////////////////////////////
//  FormularzSpecDesk_Zarz¹dzajUrz¹dzeniami.cs
//  Implementation of the Class FormularzSpecDesk_Zarz¹dzajUrz¹dzeniami
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:26
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormularzSpecDesk_Zarz¹dzajUrz¹dzeniami {

		private int Lista sprzêtów;

		public FormularzSpecDesk_Zarz¹dzajUrz¹dzeniami(){

		}

		~FormularzSpecDesk_Zarz¹dzajUrz¹dzeniami(){

		}

		public void Rozpocznij edycjê(){

		}

		public void Wyœwietl panel edycji(){

		}

	}//end FormularzSpecDesk_Zarz¹dzajUrz¹dzeniami

}//end namespace Interfejsy