///////////////////////////////////////////////////////////
//  FormulrzPrac_Zarz퉐zajWnioskami.cs
//  Implementation of the Class FormulrzPrac_Zarz퉐zajWnioskami
//  Generated by Enterprise Architect
//  Created on:      05-kwi-2026 17:01:52
//  Original author: wiktor-konieczny
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Interfejsy {
	public class FormulrzPrac_Zarz퉐zajWnioskami {

		private int Z쿽퓇ne wnioski;

		public FormulrzPrac_Zarz퉐zajWnioskami(){

		}

		~FormulrzPrac_Zarz퉐zajWnioskami(){

		}

		public void Edycja wniosku(){

		}

		public Ster_Zarz퉐zajWnioskami Ster_Zarz퉐zajWnioskami{
			get{
				return m_Ster_Zarz퉐zajWnioskami;
			}
			set{
				m_Ster_Zarz퉐zajWnioskami = value;
			}
		}

		public void WnioskiPrac(){

		}

	}//end FormulrzPrac_Zarz퉐zajWnioskami

}//end namespace Interfejsy